import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
IGNORES = {'.git', '.venv', '__pycache__', 'node_modules', 'extension.crx', 'extension.pem'}
PY_SIGNATURE = re.compile(r'^(class\s+\w+|def\s+\w+\s*\([^\)]*\))')
JS_SIGNATURE = re.compile(r'^(?:export\s+)?(?:(?:function|class)\s+\w+|(?:const|let)\s+\w+\s*=\s*(?:async\s+function|function|\([^\)]*\)\s*=>))')
COMMENT_SIG = re.compile(r'^[ \t]*#|^[ \t]*//')


def extract_signatures(path: Path):
    lines = []
    if path.suffix == '.py':
        with path.open('r', encoding='utf-8') as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith('#'):
                    continue
                match = PY_SIGNATURE.match(stripped)
                if match:
                    lines.append(stripped)
                elif stripped.startswith(('"""', "'''")):
                    lines.append(stripped)
    elif path.suffix == '.js':
        with path.open('r', encoding='utf-8') as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith('//'):
                    continue
                match = JS_SIGNATURE.match(stripped)
                if match:
                    lines.append(stripped)
                elif stripped.startswith('/*') or stripped.startswith('*'):
                    lines.append(stripped)
    return lines


def build_tree(root: Path):
    entries = []
    for path in sorted(root.iterdir()):
        if path.name in IGNORES or path.name.startswith('.') and path.name not in {'.context.md', '.cursorrules'}:
            continue
        if path.is_dir():
            entries.append(f'{path.name}/')
            for sig in extract_signatures(path):
                entries.append(f'  - {sig}')
            sub = build_tree(path)
            entries.extend([f'  {line}' for line in sub])
        elif path.is_file():
            entries.append(path.name)
            sigs = extract_signatures(path)
            entries.extend([f'  - {sig}' for sig in sigs])
    return entries


def main():
    tree = build_tree(ROOT)
    for filename in ('project_skeleton.txt', 'project_map.txt'):
        out_path = ROOT / filename
        with out_path.open('w', encoding='utf-8') as f:
            f.write('# Project Skeleton\n')
            f.write('Generated by generate_skeleton.py\n\n')
            for line in tree:
                f.write(line + '\n')
        print(f'Wrote {out_path}')


if __name__ == '__main__':
    main()
